// Code generated by protoc-gen-defaults. DO NOT EDIT.

package pb

var GreeterMethods = struct {
	SayHello       string
	SayHelloStream string
}{
	SayHello:       "/helloworld.Greeter/SayHello",
	SayHelloStream: "/helloworld.Greeter/SayHelloStream",
}

var HelloRequestFields = struct {
	Name string
}{
	Name: "name",
}

var HelloReplyFields = struct {
	Message string
}{
	Message: "message",
}

var HelloStreamRequestFields = struct {
	Name  string
	Count string
}{
	Name:  "name",
	Count: "count",
}
